--- #YAML:1.0
name:               Tree-Numbered-Tools
version:            1.03
abstract:           Perl module to create tree objects using different sources.
author:
    - Johan Kuuse <kuuse@isc.freebsd.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Javascript::Menu:  2.02
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
